"""Colab reproduction bundle for the 3D Mesh Quality Control task.

The stage rules (``docs/tasks/mesh-quality.md``) require a Colab notebook that
runs without manual edits and reproduces the uploaded predictions exactly.  This
module stages everything that notebook needs into a single zip:

* code -- ``main.py`` + the ``mesh_quality`` package,
* trained probe checkpoints, their reference probability matrices and OOF
  matrices,
* the geometry tables and label CSVs used by the light baselines,
* ``submission.csv`` exactly as uploaded, plus a manifest with md5s, the CV
  scores and the provenance (git revision).

The raw dataset is *not* shipped: the notebook downloads it from the links in
the task statement.  ``--cache`` additionally copies the frozen-DINOv3 test
feature cache next to the zip, to be uploaded separately as a fallback for
environments where the backbone download fails.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import shutil
import subprocess
import zipfile
from pathlib import Path

import numpy as np

from . import metric, model

BUNDLE = "mesh_quality_bundle.zip"
CACHE_TABLE_FILES = ("geometry_train.csv", "geometry_test.csv")
DATA_FILES = ("train.csv", "test.csv", "submission_example.csv")
CACHE_FALLBACK = "dinos_test.npz"
TRAIN_CACHE = "dinos_train.npz"
#: The shipped bundle's Colab notebook reads the legacy fp16 ``.npz`` caches;
#: after the switch to per-split cache directories these live here as archives.
LEGACY_CACHE_DIR = "backup_g8v1"


def _legacy_cache(cache_dir: Path, name: str) -> Path:
    """Locate a legacy ``.npz`` cache: live ``cache/`` first, then the archive."""
    for base in (cache_dir, cache_dir / LEGACY_CACHE_DIR):
        if (base / name).exists():
            return base / name
    raise SystemExit(f"{name} not found in {cache_dir} or {cache_dir / LEGACY_CACHE_DIR}")

BUNDLE_README = """\
# mesh-quality Colab bundle

Everything the Colab notebook needs, except the raw renders (downloaded by the
notebook from the links in the task statement).

```
main.py  src/                  solution code (import `mesh_quality` from src/)
cache/probe_<key>.pt           trained attentive probes (weights + thresholds)
cache/probs_test_<key>.npy     per-model test probabilities (regenerated by predict)
cache/reference_probs_<key>.npy  frozen copy of the reference matrix: the notebook
                               overwrites probs_test_<key>.npy when predict re-runs,
                               so the comparison target needs its own name
cache/oof_probe_<key>.npy      out-of-fold train probabilities (score check)
cache/fuse3/{fuse3.json,oof_fuse3.npy}  3-way fusion config (weights + defect and
                               decoupled quality thresholds) and its OOF matrix
cache/l4_full/refit_l4.pt      joint mesh-probe refit over all train rows
cache/l4_full/{probs_test_l4.npy,item_ids_test.npy,oof_mesh.npy}  its test / OOF outputs
cache/mesh_tokens/test/        frozen JEPA mesh tokens for the test items (~127 MB)
cache/reference_probs_l4.npy   frozen L4 test probs (same reasoning as above)
cache/geometry_{train,test}.csv  27 geometry features per item
data/{train,test}.csv          item ids + train labels
reference_submission.csv       submission as uploaded (reference for the gate)
tools/{probe_mesh,refit_mesh,fuse3}.py  mesh member + fused-threshold tooling
manifest.json                  md5s, CV scores, thresholds, git revision
```

`manifest.json -> reference` records the fused recipe: model keys `s,b,L4`, weights
`0.3/0.4/0.3`, the per-defect `thresholds`, the decoupled `quality_thresholds`
(`quality = 1` iff every `p_i < quality_threshold_i`), and which reference
probability files reproduce `reference_submission.csv`.  `manifest.json ->
dataset_links` points to the task archive the solution was trained on
(`AIC_data.tar`, one file for both splits) plus the per-split zip fallbacks.
Upload this zip somewhere public and put the link into the notebook's
`BUNDLE_URL` (or the Google Drive id into `BUNDLE_GDRIVE_ID`), then run the
notebook top to bottom.
"""


def _md5(path: Path) -> str:
    return hashlib.md5(Path(path).read_bytes()).hexdigest()


def _git_rev(task_dir: Path) -> str:
    root = Path(task_dir).resolve().parents[1]
    try:
        rev = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        dirty = subprocess.run(
            ["git", "-C", str(root), "status", "--porcelain", "--", str(Path(task_dir).resolve())],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        return rev + ("-dirty" if dirty else "")
    except Exception:  # noqa: BLE001 - git is optional bookkeeping
        return "unknown"


def _copy(src: Path, dst: Path) -> int:
    if not src.exists():
        raise SystemExit(f"missing artifact: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return src.stat().st_size


def _check_reference(
    submission: Path, probs: np.ndarray, thresholds, item_ids, quality_thresholds=None
) -> dict:
    """Verify that ``submission.csv`` is exactly the reference rule over ``probs``.

    Defects use ``probs >= thresholds``.  ``quality`` uses the decoupled rule
    (``all p_i < qt_i``) when ``quality_thresholds`` is given, else the coupled
    ``derive_quality`` identity.
    """
    if not submission.exists():
        return {"matches": None, "note": "no submission.csv to compare"}
    import pandas as pd

    sub = pd.read_csv(submission).set_index("item_id")
    ids = [str(i) for i in item_ids]
    row_of = {i: n for n, i in enumerate(ids)}
    keep = [i for i in ids if i in sub.index]
    sub = sub.loc[keep]
    probs = probs[[row_of[i] for i in keep]]
    d_ref = sub[list(metric.DEFECTS)].to_numpy(dtype=np.int8)
    d_pred = (probs >= np.asarray(thresholds)).astype(np.int8)
    same = bool(np.array_equal(d_ref, d_pred))
    if quality_thresholds is not None:
        q_pred = ((probs >= np.asarray(quality_thresholds)).any(axis=1) == 0).astype(np.int8)
    else:
        q_pred = metric.derive_quality(d_pred)
    q_ok = bool(np.array_equal(sub["quality"].to_numpy(dtype=np.int8), q_pred))
    return {
        "matches": same,
        "quality_consistent": q_ok,
        "differing_cells": int(np.abs(d_ref - d_pred).sum()),
        "rows": len(keep),
    }


def stage_cases(
    task_dir: Path,
    staging: Path,
    oof: np.ndarray,
    probs_test: np.ndarray,
    thresholds: np.ndarray,
    n_test: int = 2,
) -> list[dict]:
    """Copy a handful of illustrative renders into the bundle for the notebook.

    Cases are picked deterministically from the out-of-fold probabilities, one
    per interesting failure/success mode, so ``interpretation.ipynb`` can show
    real renders without downloading the 2 GB test archive.  Returns the rows
    written to ``cases.csv``.  ``oof``/``probs_test``/``thresholds`` come from
    the shipped reference (probe or fusion), so the cases always describe the
    model the notebook reproduces.
    """
    import pandas as pd

    labels = pd.read_csv(task_dir / "data" / "train.csv").set_index("item_id")
    ids = np.asarray(labels.index.astype(str))
    y = labels.loc[ids, list(metric.DEFECTS)].to_numpy(dtype=np.int8)
    yq = metric.derive_quality(y)
    oof = np.asarray(oof, dtype=np.float32)
    thr = np.asarray(thresholds, dtype=np.float32)
    d_pred = (oof >= thr).astype(np.int8)
    q_pred = metric.derive_quality(d_pred)

    picked: list[dict] = []

    def take(column: str, want_true: int, want_pred: int, reason: str, rank, quality: bool = False) -> None:
        """Pick one candidate index (via ``rank(candidates) -> position``) and record it."""
        if quality:
            cand = np.where((yq == want_true) & (q_pred == want_pred))[0]
        else:
            k = metric.DEFECTS.index(column)
            cand = np.where((y[:, k] == want_true) & (d_pred[:, k] == want_pred))[0]
        if len(cand) == 0:
            print(f"[deliver] cases: no candidate for {reason}")
            return
        idx = int(cand[max(int(rank(cand)), 0)])
        picked.append({"item_id": str(ids[idx]), "idx": idx, "reason": reason})

    take("noisy", 1, 1, "верное срабатывание: шум (частый класс)", lambda c: int(np.argmax(oof[c, metric.DEFECTS.index('noisy')])))
    take("noisy", 0, 0, "верное молчание: чистый объект", lambda c: int(np.argmax(oof[c].max(1) * -1)))
    take("artifacts", 1, 0, "пропуск: локальный дефект `artifacts` не найден", lambda c: int(np.argmax(oof[c, metric.DEFECTS.index('artifacts')] * -1)))
    take("artifacts", 0, 1, "ложное срабатывание: `artifacts` без разметки", lambda c: int(np.argmax(oof[c, metric.DEFECTS.index('artifacts')])))
    take("open", 1, 0, "пропуск: `open` не найден", lambda c: int(np.argmax(oof[c, metric.DEFECTS.index('open')] * -1)))
    take("scale", 1, 0, "пропуск: редкий `scale`", lambda c: int(np.argmax(oof[c, metric.DEFECTS.index('scale')] * -1)))
    take("", 0, 1, "`quality`: дефекты есть, предсказано «чисто»", lambda c: int(np.argmax(oof[c].sum(1) * -1)), quality=True)
    take("", 1, 0, "`quality`: чисто, предсказаны дефекты", lambda c: int(np.argmax(oof[c].sum(1))), quality=True)

    probs_test = np.asarray(probs_test, dtype=np.float32)
    test_ids = np.asarray(pd.read_csv(task_dir / "data" / "test.csv")["item_id"].astype(str))
    for name in ("artifacts", "open")[:n_test]:
        k = metric.DEFECTS.index(name)
        best = int(np.argmax(probs_test[:, k]))
        picked.append({"item_id": str(test_ids[best]), "idx": best, "reason": f"тест: уверенный `{name}`", "test": True})

    rows = []
    for case in picked:
        i, split = case["idx"], "test" if case.get("test") else "train"
        src = task_dir / "data" / split / f"{case['item_id']}.png"
        if not src.exists():
            print(f"[deliver] cases: {src} missing, skipped")
            continue
        dst = staging / "data" / split / src.name
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        probs = probs_test[i] if split == "test" else oof[i]
        row = {
            "item_id": case["item_id"],
            "split": split,
            "reason": case["reason"],
            "true_defects": "" if split == "test" else " ".join(metric.DEFECTS[j] for j in np.where(y[i] > 0)[0]),
            "true_quality": "" if split == "test" else int(yq[i]),
            "pred_defects": " ".join(metric.DEFECTS[j] for j in np.where(d_pred[i] if split == "train" else (probs >= thr))[0]),
            **{name: round(float(probs[j]), 4) for j, name in enumerate(metric.DEFECTS)},
        }
        rows.append(row)
    return rows


def stage(args) -> None:
    """Build ``<out>/mesh_quality_bundle.zip`` (+ optional fallback cache copy)."""
    import pandas as pd

    task_dir = Path(args.task_dir)
    cache_dir = task_dir / "cache"
    out_dir = Path(args.out)
    staging = out_dir / "mesh_quality"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    keys = [k.strip() for k in args.models.split(",") if k.strip()]
    if not keys:
        raise SystemExit("--models needs at least one key, e.g. s,b")
    ref_key = args.ref_model or keys[0]
    ref_models = [k.strip() for k in ref_key.split("+") if k.strip()]
    if not set(ref_models) <= set(keys):
        raise SystemExit(f"--ref-model {ref_key} is not covered by --models {keys}")

    # The reference is either one probe (thresholds live in its checkpoint), a
    # probe fusion (thresholds live in the fuse_<tag>.json written by `fuse`),
    # or the 3-way fuse3 fusion (mesh member + decoupled quality thresholds).
    import torch

    fused = len(ref_models) > 1
    ref_fuse3 = bool(getattr(args, "ref_fuse3", False))
    quality_thresholds = None
    if ref_fuse3:
        fuse3_json = cache_dir / "fuse3" / "fuse3.json"
        fusion = json.loads(fuse3_json.read_text())
        thresholds = np.asarray([fusion["thresholds"][k] for k in metric.DEFECTS], dtype=np.float32)
        quality_thresholds = np.asarray([fusion["quality_thresholds"][k] for k in metric.DEFECTS], dtype=np.float32)
        ref_weights = [fusion["weights"]["s"], fusion["weights"]["b"], fusion["weights"]["l4"]]
        ref_cv = {"score": fusion["oof_score"], "artefact_f1_weighted": fusion["oof_artefact"],
                  "quality_f1": fusion["oof_quality"], "half_split_dual": fusion["half_split_dual"],
                  "half_split_coupled": fusion["half_split_coupled"]}
        ref_key = "fuse3"
        ref_models = ["s", "b", "L4"]
        ref_probs_file = cache_dir / "fuse3" / "probs_test_fuse3.npy"
        ref_oof_file = cache_dir / "fuse3" / "oof_fuse3.npy"
        fused = True
    elif fused:
        fusion = json.loads((cache_dir / f"fuse_{ref_key}.json").read_text())
        thresholds = fusion["thresholds"]
        ref_weights = fusion["weights"]
        ref_cv = fusion["cv"]
        ref_probs_file = cache_dir / f"probs_test_fuse_{ref_key}.npy"
        ref_oof_file = cache_dir / f"oof_fuse_{ref_key}.npy"
    else:
        checkpoint = torch.load(cache_dir / f"probe_{ref_key}.pt", map_location="cpu", weights_only=False)
        thresholds = checkpoint["thresholds"]
        ref_weights = [1.0]
        ref_cv = checkpoint.get("cv", {})
        ref_probs_file = cache_dir / f"probs_test_{ref_key}.npy"
        ref_oof_file = cache_dir / f"oof_probe_{ref_key}.npy"
    probs_ref = np.load(ref_probs_file).astype(np.float32)
    oof_ref = np.load(ref_oof_file).astype(np.float32)
    print(f"[deliver] reference {ref_key}: weights {ref_weights}, CV {ref_cv.get('score', float('nan')):.3f}")

    files: dict[str, dict] = {}

    def record(name: str, src: Path, dst: Path) -> None:
        size = _copy(src, dst)
        files[name] = {"bytes": size, "md5": _md5(dst)}
        print(f"[deliver] {name:<34} {size / 1e6:8.2f} MB  {files[name]['md5']}")

    # --- code -------------------------------------------------------------- #
    record("main.py", task_dir / "main.py", staging / "main.py")
    for src in sorted((task_dir / "src" / "mesh_quality").glob("*.py")):
        record(f"src/mesh_quality/{src.name}", src, staging / "src" / "mesh_quality" / src.name)

    # --- trained probes and reference matrices ----------------------------- #
    for key in keys:
        record(f"cache/probe_{key}.pt", cache_dir / f"probe_{key}.pt", staging / "cache" / f"probe_{key}.pt")
        record(f"cache/probs_test_{key}.npy", cache_dir / f"probs_test_{key}.npy", staging / "cache" / f"probs_test_{key}.npy")
        record(f"cache/oof_probe_{key}.npy", cache_dir / f"oof_probe_{key}.npy", staging / "cache" / f"oof_probe_{key}.npy")
    # Frozen copy of the reference matrix: ``predict`` in the notebook rewrites
    # ``probs_test_<key>.npy``, so the comparison target must not be that name.
    record(
        f"cache/reference_probs_{ref_key}.npy",
        ref_probs_file,
        staging / "cache" / f"reference_probs_{ref_key}.npy",
    )
    if fused and not ref_fuse3:
        record(f"cache/fuse_{ref_key}.json", cache_dir / f"fuse_{ref_key}.json", staging / "cache" / f"fuse_{ref_key}.json")
    for src in sorted(cache_dir.glob("oof_fuse_*.npy")) + sorted(cache_dir.glob("probs_test_fuse_*.npy")):
        record(f"cache/{src.name}", src, staging / "cache" / src.name)
    if ref_fuse3:
        record("cache/fuse3/fuse3.json", fuse3_json, staging / "cache" / "fuse3" / "fuse3.json")
        record("cache/fuse3/oof_fuse3.npy", ref_oof_file, staging / "cache" / "oof_fuse3.npy")
        record("cache/l4_full/refit_l4.pt", cache_dir / "l4_full" / "refit_l4.pt",
               staging / "cache" / "l4_full" / "refit_l4.pt")
        record("cache/l4_full/probs_test_l4.npy", cache_dir / "l4_full" / "probs_test_l4.npy",
               staging / "cache" / "l4_full" / "probs_test_l4.npy")
        # Frozen copy for the notebook's in-refit L4 predict (which overwrites
        # ``cache/l4_full/probs_test_l4.npy`` under the same reasoning as
        # ``reference_probs_fuse3.npy`` above).
        record("cache/reference_probs_l4.npy", cache_dir / "l4_full" / "probs_test_l4.npy",
               staging / "cache" / "reference_probs_l4.npy")
        record("cache/l4_full/item_ids_test.npy", cache_dir / "l4_full" / "item_ids_test.npy",
               staging / "cache" / "l4_full" / "item_ids_test.npy")
        record("cache/l4_full/oof_mesh.npy", cache_dir / "l4_full" / "oof_mesh.npy",
               staging / "cache" / "l4_full" / "oof_mesh.npy")
        mesh_dir = cache_dir / "mesh_tokens" / "test"
        for f in sorted(mesh_dir.iterdir()):
            if f.is_file():
                record(f"cache/mesh_tokens/test/{f.name}", f, staging / "cache" / "mesh_tokens" / "test" / f.name)
        for name in ("probe_mesh.py", "refit_mesh.py", "fuse3.py"):
            record(f"tools/{name}", task_dir / "tools" / name, staging / "tools" / name)
    for name in CACHE_TABLE_FILES:
        record(f"cache/{name}", cache_dir / name, staging / "cache" / name)
    if (cache_dir / "oof_geometry.npy").exists():
        record("cache/oof_geometry.npy", cache_dir / "oof_geometry.npy", staging / "cache" / "oof_geometry.npy")

    # --- dataset tables ---------------------------------------------------- #
    for name in DATA_FILES:
        src = task_dir / "data" / name
        if src.exists():
            record(f"data/{name}", src, staging / "data" / name)

    # --- notebooks --------------------------------------------------------- #
    nb_dir = task_dir / "notebooks"
    for nb in (sorted(nb_dir.glob("*.ipynb")) if nb_dir.exists() else []):
        record(f"notebooks/{nb.name}", nb, staging / "notebooks" / nb.name)

    # --- interpretive cases (renders + selection table) -------------------- #
    cases = stage_cases(task_dir, staging, oof_ref, probs_ref, thresholds)
    if cases:
        import pandas as pd

        cases_path = staging / "cases.csv"
        pd.DataFrame(cases).to_csv(cases_path, index=False)
        print(f"[deliver] cases.csv                                  {len(cases)} rows")

    # --- the submitted file, verified against the reference probabilities --- #
    submission = Path(args.submission)
    test_ids = np.asarray(pd.read_csv(task_dir / "data" / "test.csv")["item_id"].astype(str))
    check = _check_reference(submission, probs_ref, thresholds, test_ids, quality_thresholds)
    if check.get("matches") is False:
        print(f"[deliver] WARNING: {submission.name} differs from {ref_probs_file.name} "
              f"in {check['differing_cells']} cells -- the gate would fail")
    else:
        print(f"[deliver] reference check: {submission.name} == {ref_probs_file.name} >= thresholds")
    record("reference_submission.csv", submission, staging / "reference_submission.csv")

    # --- manifest ---------------------------------------------------------- #
    manifest = {
        "created": dt.datetime.now().isoformat(timespec="seconds"),
        "git_rev": _git_rev(task_dir),
        "train_seed": model.SEED,  # training seed of the shipped probe (code default)
        "models": keys,
        "reference": {
            "model": ref_key,
            "models": ref_models,
            "weights": ref_weights,
            "fused": fused,
            "thresholds": [float(t) for t in thresholds],
            "quality_thresholds": None if quality_thresholds is None else [float(t) for t in quality_thresholds],
            "cv": ref_cv,
            "submission_check": check,
            "reference_submission_md5": _md5(submission),
            "reference_probs": f"cache/reference_probs_{ref_key}.npy",
            "reference_probs_md5": _md5(staging / "cache" / f"reference_probs_{ref_key}.npy"),
            "reference_probs_l4": "cache/reference_probs_l4.npy" if ref_fuse3 else None,
            "reference_probs_l4_md5": (
                _md5(staging / "cache" / "reference_probs_l4.npy") if ref_fuse3 else None
            ),
            "reference_oof": f"cache/{ref_oof_file.name}",
        },
        "files": files,
        "cases": cases,
        "dataset_links": {
            # Источник, на котором обучено решение: один tar на train+test (26.6 ГиБ).
            "source": "https://rndml-team-xr.obs.ru-moscow-1.hc.sbercloud.ru/mazurov/AIC_data.tar",
            # Запасные официальные zip-архивы (по сплитам).
            "test_zip": "https://disk.360.yandex.ru/d/rUSPxzoDTHK8UQ",
            "train_zip": "https://disk.360.yandex.ru/d/CeZVSNyRGjrLUw",
        },
        "cache_fallback": CACHE_FALLBACK if args.cache else None,
    }
    (staging / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
    (staging / "README.md").write_text(BUNDLE_README)

    bundle = out_dir / BUNDLE
    with zipfile.ZipFile(bundle, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in sorted(staging.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(out_dir))
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
    print(f"[deliver] {bundle}  {bundle.stat().st_size / 1e6:.2f} MB  md5 {_md5(bundle)}")
    print(f"[deliver] reference model {ref_key}, thresholds "
          + " ".join(f"{float(t):.3f}" for t in thresholds))

    if args.cache:
        dst = out_dir / CACHE_FALLBACK
        size = _copy(_legacy_cache(cache_dir, CACHE_FALLBACK), dst)
        print(f"[deliver] {CACHE_FALLBACK} (upload separately)  {size / 1e6:.2f} MB  md5 {_md5(dst)}")
    if getattr(args, "train_cache", False):
        dst = out_dir / TRAIN_CACHE
        size = _copy(_legacy_cache(cache_dir, TRAIN_CACHE), dst)
        print(f"[deliver] {TRAIN_CACHE} (upload separately)  {size / 1e6:.2f} MB  md5 {_md5(dst)}")

    print(
        "\n[deliver] next: upload the zip (and optionally the cache) to a public link, then\n"
        "          set BUNDLE_URL / BUNDLE_GDRIVE_ID and CACHE_URL in notebooks/colab_solution.ipynb."
    )
